import { Aircraft, Flight, Alert, WeatherData, ChatMessage } from "@/types";

const today = new Date().toISOString().split("T")[0];

export const mockAircraft: Aircraft[] = [
  {
    id: "ac-1",
    fbo_id: "fbo-1",
    tail_number: "N12345",
    make: "Cessna",
    model: "172S Skyhawk",
    category: "airplane",
    total_flight_hours: 4892,
    status: "available",
    last_oil_change_hours: 4850,
    last_100hr_inspection_hours: 4800,
    last_annual_inspection_hours: 4500,
    adsb_enabled: true,
    icao24_hex: "A12345",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "ac-2",
    fbo_id: "fbo-1",
    tail_number: "N67890",
    make: "Piper",
    model: "PA-28 Cherokee",
    category: "airplane",
    total_flight_hours: 3210,
    status: "available",
    last_oil_change_hours: 3190,
    last_100hr_inspection_hours: 3150,
    last_annual_inspection_hours: 3000,
    adsb_enabled: true,
    icao24_hex: "A67890",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "ac-3",
    fbo_id: "fbo-1",
    tail_number: "N24680",
    make: "Robinson",
    model: "R44 Raven II",
    category: "helicopter",
    total_flight_hours: 1856,
    status: "maintenance",
    last_oil_change_hours: 1840,
    last_100hr_inspection_hours: 1800,
    last_annual_inspection_hours: 1700,
    adsb_enabled: true,
    icao24_hex: "A24680",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "ac-4",
    fbo_id: "fbo-1",
    tail_number: "N13579",
    make: "Cessna",
    model: "182T Skylane",
    category: "airplane",
    total_flight_hours: 2543,
    status: "flying",
    last_oil_change_hours: 2520,
    last_100hr_inspection_hours: 2500,
    last_annual_inspection_hours: 2400,
    adsb_enabled: true,
    icao24_hex: "A13579",
    created_at: "2024-01-01T00:00:00Z",
  },
];

export const mockFlights: Flight[] = [
  {
    id: "fl-1",
    fbo_id: "fbo-1",
    aircraft_id: "ac-1",
    customer_name: "John Smith",
    customer_email: "john@email.com",
    customer_phone: "+15551234567",
    flight_date: today,
    flight_time: "09:00",
    duration_minutes: 60,
    service_type: "discovery",
    status: "scheduled",
    created_at: "2024-02-15T00:00:00Z",
    aircraft: mockAircraft[0],
  },
  {
    id: "fl-2",
    fbo_id: "fbo-1",
    aircraft_id: "ac-2",
    customer_name: "Sarah Lee",
    customer_email: "sarah@email.com",
    customer_phone: "+15559876543",
    flight_date: today,
    flight_time: "10:30",
    duration_minutes: 120,
    service_type: "rental",
    status: "scheduled",
    created_at: "2024-02-14T00:00:00Z",
    aircraft: mockAircraft[1],
  },
  {
    id: "fl-3",
    fbo_id: "fbo-1",
    aircraft_id: "ac-1",
    customer_name: "Mike Chen",
    customer_email: "mike@email.com",
    customer_phone: "+15555551234",
    flight_date: today,
    flight_time: "14:00",
    duration_minutes: 120,
    service_type: "rental",
    status: "scheduled",
    created_at: "2024-02-13T00:00:00Z",
    aircraft: mockAircraft[0],
  },
  {
    id: "fl-4",
    fbo_id: "fbo-1",
    aircraft_id: "ac-4",
    customer_name: "Emily Davis",
    customer_email: "emily@email.com",
    flight_date: today,
    flight_time: "11:00",
    duration_minutes: 90,
    service_type: "lesson",
    status: "scheduled",
    created_at: "2024-02-12T00:00:00Z",
    aircraft: mockAircraft[3],
  },
  {
    id: "fl-5",
    fbo_id: "fbo-1",
    aircraft_id: "ac-2",
    customer_name: "Alex Johnson",
    customer_email: "alex@email.com",
    flight_date: today,
    flight_time: "15:30",
    duration_minutes: 60,
    service_type: "discovery",
    status: "scheduled",
    created_at: "2024-02-11T00:00:00Z",
    aircraft: mockAircraft[1],
  },
  {
    id: "fl-6",
    fbo_id: "fbo-1",
    aircraft_id: "ac-1",
    customer_name: "Lisa Wang",
    customer_email: "lisa@email.com",
    flight_date: today,
    flight_time: "16:30",
    duration_minutes: 60,
    service_type: "lesson",
    status: "scheduled",
    created_at: "2024-02-10T00:00:00Z",
    aircraft: mockAircraft[0],
  },
  {
    id: "fl-7",
    fbo_id: "fbo-1",
    aircraft_id: "ac-4",
    customer_name: "David Park",
    customer_email: "david@email.com",
    flight_date: today,
    flight_time: "08:00",
    duration_minutes: 120,
    service_type: "rental",
    status: "completed",
    actual_start_time: `${today}T08:00:00Z`,
    actual_end_time: `${today}T09:45:00Z`,
    flight_hours: 1.75,
    created_at: "2024-02-09T00:00:00Z",
    aircraft: mockAircraft[3],
  },
  {
    id: "fl-8",
    fbo_id: "fbo-1",
    aircraft_id: "ac-2",
    customer_name: "Rachel Kim",
    customer_email: "rachel@email.com",
    flight_date: today,
    flight_time: "17:30",
    duration_minutes: 60,
    service_type: "tour",
    status: "scheduled",
    created_at: "2024-02-08T00:00:00Z",
    aircraft: mockAircraft[1],
  },
];

export const mockAlerts: Alert[] = [
  {
    id: "al-1",
    fbo_id: "fbo-1",
    aircraft_id: "ac-1",
    alert_type: "maintenance",
    priority: "high",
    message: "N12345 needs oil change in 8 flight hours (at 4,900 hrs)",
    status: "active",
    created_at: new Date().toISOString(),
    aircraft: mockAircraft[0],
  },
  {
    id: "al-2",
    fbo_id: "fbo-1",
    alert_type: "weather",
    priority: "medium",
    message: "Winds forecast 25kts gusting 35kts at 3:00 PM. 3 afternoon flights may be affected.",
    status: "active",
    created_at: new Date().toISOString(),
  },
  {
    id: "al-3",
    fbo_id: "fbo-1",
    aircraft_id: "ac-3",
    alert_type: "maintenance",
    priority: "low",
    message: "N24680 100-hour inspection due in 56 flight hours",
    status: "active",
    created_at: new Date().toISOString(),
    aircraft: mockAircraft[2],
  },
];

export const mockWeather: WeatherData = {
  raw_metar: "KPDK 161553Z 27012G18KT 10SM FEW045 SCT250 22/08 A3001",
  station: "KPDK",
  temperature: 22,
  dewpoint: 8,
  wind_direction: 270,
  wind_speed: 12,
  wind_gust: 18,
  visibility: 10,
  ceiling: 4500,
  flight_category: "VFR",
  conditions: "Few clouds at 4,500ft, scattered at 25,000ft",
};

export const mockConversation: ChatMessage[] = [];

export function getFlightsByStatus(status: string): Flight[] {
  return mockFlights.filter((f) => f.status === status);
}

export function getActiveAlerts(): Alert[] {
  return mockAlerts.filter((a) => a.status === "active");
}

export function getAircraftByStatus(status: string): Aircraft[] {
  return mockAircraft.filter((a) => a.status === status);
}
